services:
  - type: web
    name: isharat-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    repo: https://github.com/alisabaha/isharat-bo
    branch: main
    autoDeploy: true
